import sqlite3
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI()

@app.get("/")
def read_root():
    return {"name": "Task API", "version": "1.0", "endpoints": ["/tasks"]}

@app.get("/health")
def health_check():
    return {"status": "ok"}

def init_db():
    conn = sqlite3.connect("tasks.db")
    cursor = conn.cursor()
    
    # Table banayein agar nahi bani hui
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            done INTEGER NOT NULL
        )
    ''')
    
    # Agar table khali hai toh 3 sample tasks daalein
    cursor.execute("SELECT COUNT(*) FROM tasks")
    if cursor.fetchone()[0] == 0:
        sample_tasks = [
            ("Task 1", 0),
            ("Task 2", 1),
            ("Task 3", 0)
        ]
        cursor.executemany("INSERT INTO tasks (title, done) VALUES (?, ?)", sample_tasks)
        conn.commit()
        
    conn.close()

init_db()

# Helper function (Database rows ko dictionary banata hai)
def dict_factory(cursor, row):
    return {col[0]: row[idx] for idx, col in enumerate(cursor.description)}

@app.get("/tasks")
def get_tasks():
    conn = sqlite3.connect("tasks.db")
    conn.row_factory = dict_factory
    cursor = conn.cursor()
    
    cursor.execute("SELECT * FROM tasks")
    tasks = cursor.fetchall()
    
    for task in tasks:
        task["done"] = bool(task["done"])
        
    conn.close()
    return tasks

@app.get("/tasks/{id}")
def get_task(id: int):
    conn = sqlite3.connect("tasks.db")
    conn.row_factory = dict_factory
    cursor = conn.cursor()
    
    cursor.execute("SELECT * FROM tasks WHERE id=?", (id,))
    task = cursor.fetchone()
    conn.close()
    
    if task is None:
        raise HTTPException(status_code=404, detail="Task not found")
        
    task["done"] = bool(task["done"])
    return task

class Task(BaseModel):
    title: str
    done: bool = False

@app.post("/tasks", status_code=201)
def create_task(task: Task):
    # Validation unchanged
    if not task.title.strip():
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    
    conn = sqlite3.connect("tasks.db")
    cursor = conn.cursor()
    
    # Parameterized query to insert data
    cursor.execute("INSERT INTO tasks (title, done) VALUES (?, ?)", (task.title, int(task.done)))
    conn.commit()
    
    # Get the ID generated by the database
    new_id = cursor.lastrowid
    conn.close()
    
    return {"id": new_id, "title": task.title, "done": task.done}

@app.put("/tasks/{id}")
def update_task(id: int, updated_task: Task):
    if not updated_task.title.strip():
        raise HTTPException(status_code=400, detail="Title cannot be empty")
        
    conn = sqlite3.connect("tasks.db")
    conn.row_factory = dict_factory
    cursor = conn.cursor()
    
    # Check if task exists
    cursor.execute("SELECT * FROM tasks WHERE id=?", (id,))
    if cursor.fetchone() is None:
        conn.close()
        raise HTTPException(status_code=404, detail="Task not found")
        
    # Update the task
    cursor.execute("UPDATE tasks SET title=?, done=? WHERE id=?", (updated_task.title, int(updated_task.done), id))
    conn.commit()
    
    # Fetch and return the updated task
    cursor.execute("SELECT * FROM tasks WHERE id=?", (id,))
    task = cursor.fetchone()
    conn.close()
    
    task["done"] = bool(task["done"])
    return task

@app.delete("/tasks/{id}", status_code=204)
def delete_task(id: int):
    conn = sqlite3.connect("tasks.db")
    cursor = conn.cursor()
    
    # Check if task exists
    cursor.execute("SELECT * FROM tasks WHERE id=?", (id,))
    if cursor.fetchone() is None:
        conn.close()
        raise HTTPException(status_code=404, detail="Task not found")
        
    # Delete the task
    cursor.execute("DELETE FROM tasks WHERE id=?", (id,))
    conn.commit()
    conn.close()
    return